jukebox:
    container_name: jukebox
    build: ./docker/jukebox
    privileged: true
    ports:
        - "8080:80"
        - "3000:3000"
        - "5858:5858"
    volumes:
        - ./:/var/www/html
